# SITE SETTINGS
title: Styliani Christina Fragkouli                        # Title in top navigation bar (navbar) and <head>
description: A Physicist playing with ML & Bioinformatics # Site description in <head>
author: Styliani Christina Fragkouli                     # Used for copyright statement in footer
url: "https://sfragkoul.github.io"  # No slash at the end
# baseurl: "/petridish"                 # Only required if your site is on a subdomain e.g. https://username.github.io/sitename
                                        # which has url: "https://username.github.io" (no slash) and baseurl: "/sitename" (leading slash)
                                        # A baseurl affects internal links, see http://peterdesmet.github.io/petridish/about/#links

# SOCIAL PROFILES
email: sfragkoul@certh.gr         # Social icon in footer
twitter_username: scfragkoul       # Social icon in footer
github_username: sfragkoul       # Social icon in footer

# THEME SETTINGS (ALL OPTIONAL)
posts_on_home: 3                        # Show x number of latest posts on homepage, can be 0
tweets_on_home: true                    # Show Twitter feed of twitter_username on homepage
archive_permalink: /blog/               # Permalink of page using archive.html layout, required when using post categories
logo: /assets/img/groupLogo/helix.png # Logo in navbar, will be displayed with 30px height
colors:
  links: "#007bff"                      # Color for links: use a readable color that contrasts well with dark text
  banner: "#007bff"                     # Background color for page banners: use color that contrasts well with white
  footer: "#6c757d"                     # Background color for footer: use color that contrasts well with white
rounded_corners: true                   # Enable (default) rounded corners on boxes and buttons

# BUILD SETTINGS
markdown: kramdown
plugins:                                # If you build your site on gh-pages, only use these plugins: https://pages.github.com/versions/
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-scholar
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - petridish.gemspec

exclude: [vendor]

# Original file: https://github.com/citation-style-language/styles-distribution
# Information: https://www.mghassany.com/blog/From-Wordpress-to-Jekyll/
scholar:
  style: assets/bibliography/ieee.csl
  locale: en

  sort_by: none
  order: descending
  #group_by: year
  bibliography_list_tag: ul

  source: _bibliography
  bibliography: references.bib
  # bibliography_template: "{{reference}}"
  bibliography_template: bib

  use_raw_bibtex_entry: true

  replace_strings: true
  join_strings:    true

  query: "@*"

# FRONTMATTER DEFAULTS
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:year/:slug/"   # Use /blog/yyyy/{filename}/ as permalink for all posts
  -
    scope:
      path: ""
    values:
      layout: "default"                 # Only required for Petridish website, implied for sites using a theme
